### ISSUE TITLE
Need to distribute public keys across workstations

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/PoonLab#46]
Please deposit your public key in your `~/.ssh` folder on Shinji

**Comment by 0ldM4j0r** [comment]
As discussed in the one one one meeting I can distribute the public keys of @gtng92 @mavino @Abayomi-Olabode. 

@ArtPoon would you like me to do yours as well?

**Comment by ArtPoon** [comment]
yes please

**Comment by 0ldM4j0r** [comment]
As of now every full time member in the lab should be able to access their respective accounts on the linux workstations via ssh. I tested it on @gtng92 machine and it works.
