### ISSUE TITLE
Nagisa keeps showing "System program problem detected" upon first login

### ISSUE THREAD

**Issue by R3IDV3** [PoonLab/PoonLab#51]
After logging in for the first time each morning, Nagisa is displaying System program problem detected with a report problem button. Perhaps there are [old crashes](https://askubuntu.com/questions/133385/getting-system-program-problem-detected-pops-up-regularly-after-upgrade/369297) throwing errors?

**Comment by jpalme56** [comment]
I noticed this too. There seem to be more copies of the same message now as well.
