### ISSUE TITLE
Update Scyld ClusterWare to version 7.3.6

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/PoonLab#59]
There's a known memory leak when launching subprocesses from Python3 in Scyld CW
See https://github.com/cfe-lab/Kive/issues/709

**Comment by donkirkby** [comment]
In case they're helpful, here's a few more details that aren't on that issue.

The final script I used to reproduce the memory leak:

``` 
from subprocess import check_output, STDOUT 

from datetime import datetime, timedelta 

command_args = ["python3", "-c", "print('Hello, World!')"] 
end_time = datetime.now() + timedelta(seconds=120) 
print('Started.') 

while datetime.now() < end_time: 
report = check_output(command_args, stderr=STDOUT) 
assert report.decode('utf8') == 'Hello, World!\n', report 

print('Done.') 
``` 

I ran that on a compute node for two minutes, and checked the available memory before and after: 

``` 
$ bpsh 3 bash -c "free && python3 copy_test2.py && free" 
total used free shared buff/cache available 
Mem: 8169396 325004 7639428 120088 204964 7529516 
Swap: 0 0 0 
Started. 
Done. 
total used free shared buff/cache available 
Mem: 8169396 562104 7401556 120088 205736 7291648 
Swap: 0 0 0 
``` 

You can see that it consumed over 200MB in two minutes. The available memory does not go up if I wait longer, the only way we've found to release it is a reboot of the compute node. 

We first upgraded to 7.4.4, and that didn't work with the old compute nodes. We downgraded to 7.4.2, and that worked. Hopefully, you have new enough hardware that either will work.

**Comment by ArtPoon** [comment]
Thanks @donkirkby.  I am going to try to avoid doing a kernel upgrade as per Scyld instructions. The hardware is pretty new so hopefully we won't encounter this problem either way.

**Comment by ArtPoon** [comment]
On running `yum --disablerepo=cw* --exclude=kernel-* update`, got the following error:
```
--> Finished Dependency Resolution
Error: Package: libgpod-0.8.3-14.el7.x86_64 (@epel)
           Requires: libplist.so.1()(64bit)
           Removing: libplist-1.10-4.el7.x86_64 (@anaconda)
               libplist.so.1()(64bit)
           Updated By: libplist-1.12-3.el7.x86_64 (base)
              ~libplist.so.3()(64bit)
Error: Package: libgpod-0.8.3-14.el7.x86_64 (@epel)
           Requires: libusbmuxd.so.2()(64bit)
           Removing: usbmuxd-1.0.8-11.el7.x86_64 (@anaconda)
               libusbmuxd.so.2()(64bit)
           Obsoleted By: usbmuxd-1.1.0-1.el7.x86_64 (base)
               Not found
Error: Package: libgpod-0.8.3-14.el7.x86_64 (@epel)
           Requires: libimobiledevice.so.4()(64bit)
           Removing: libimobiledevice-1.1.5-6.el7.x86_64 (@anaconda)
               libimobiledevice.so.4()(64bit)
           Updated By: libimobiledevice-1.2.0-1.el7.x86_64 (base)
              ~libimobiledevice.so.6()(64bit)
 You could try using --skip-broken to work around the problem
```
A quick Google search determined this is a [known issue](https://wiki.centos.org/Manuals/ReleaseNotes/CentOS7) with CentOS.  Following Release Notes recommendation to run `yum downgrade libgpod`.

**Comment by ArtPoon** [comment]
Got stuck with a full-screen popup with "authentication required to set the network proxy used for downloading packages" for a while.  Entering the correct credentials kept raising the same pop-up.  After a while cancelling this dialog returned me back to the desktop.  Since this happened while updating the system, I'm guessing it was caused by something being overwritten.

**Comment by ArtPoon** [comment]
```
[root@BEVi art]# yum update install-scyld
Loaded plugins: fastestmirror, langpacks, priorities
Loading mirror speeds from cached hostfile
 * base: centos.mirror.ca.planethoster.net
 * epel: mirror.csclub.uwaterloo.ca
 * extras: centos.mirror.rafal.ca
 * updates: centos.mirror.netelligent.ca
63 packages excluded due to repository priority protections
No packages marked for update
[root@BEVi art]# install-scyld -u
== Gathering the list of potential rpm updates (may take a minute or two)...
== /etc/yum.conf is configured to retain multiple kernels: OK

This script updates Penguin Computing's Scyld ClusterWare 7.

Read ClusterWare release notes and guides for important notices:
http://www.penguincomputing.com/services-support/documentation/

All modified files will be backed up as $FILENAME.scyld-backup

This script updates a new kernel. If your cluster uses any 3rd-party drivers
(e.g., Ethernet, Infiniband, GPU, Panasas, parallel storage) or application
software, then you must be certain that those software components are
compatible with the specific kernel version (kernel.x86_64)
about to be installed.

== Do you want to proceed? (required) [Y|n]: y
!! Until the cluster updates to ClusterWare 7.4 or beyond, we strongly
!! recommend 'systemctl disable clusterware' followed by rebooting the
!! master node. After rebooting and 'clusterware' now not running, then
!! 'update-scyld' again and 'systemctl enable clusterware'. If a new
!! kernel has been installed, then again reboot the master node to execute
!! that new kernel. If no new kernel has been installed, then
!! 'systemctl start clusterware' and resume cluster operations.
[root@BEVi art]# systemctl disable clusterware
clusterware.service is not a native service, redirecting to /sbin/chkconfig.
Executing /sbin/chkconfig clusterware off
```

**Comment by ArtPoon** [comment]
Ha ha, response has to be an upper case `Y`

**Comment by ArtPoon** [comment]
Rebooted with updated CW kernel
```
[art@BEVi ~]$ uname -a
Linux BEVi 3.10.0-693.17.1.el7.744g0000.x86_64 #1 SMP Fri Jan 26 19:41:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
Compute nodes not coming online:
```
[art@BEVi ~]$ bpstat 
Node(s)                        Status       Mode       User        Group
0-3                            down         ---------- root        root   
```

**Comment by wrpscott** [comment]
Art, the solution is to run a 7.4.2 kernel with your OS upgraded to 7.4.4. PC gave me this info:
a) download and install the 742 kernel
mkdir 742g; cd 742g;
yumdownloader --arch=x86_64 kernel-*742g* bproc-*742g* kmod-*742g*
rpm -iv --force kernel-* kmod-*
rpm -Uv --force bproc*
b) config grub
edit /etc/default/grub to ensure the lines are present:
GRUB_DEFAULT=saved
GRUB_SAVEDEFAULT=true
(solve a longstanding RHEL problem involving grub:
(cd /boot/grub2; mv grubenv grubenv.bak; ln -s ../efi/EFI/centos/grubenv grubenv)
c) tell grub to rebuild its menu
grub2-mkconfig -o /boot/grub2/grub.cfg

d) reboot from the head node console, and choose the new 742 kernel. From now on, this will be the default kernel.
e) Now start clusterware and try to boot a compute node... hopefully this will now work!

**Comment by wrpscott** [comment]
Note that in the above, the stars * are missing in kernel- STAR742gSTAR    bproc-STAR742gSTAR  and kmod-STAR742gSTAR

**Comment by ArtPoon** [comment]
Thanks very much @wrpscott !!

**Comment by ArtPoon** [comment]
Compute nodes came online after my colleague in IT power cycled the servers - so far it looks like the cluster is up and running again but will keep an eye out for this issue.  Closing for now.
