### ISSUE TITLE
Issue with Shinji's graphics card

### ISSUE THREAD

**Issue by helenhe96** [PoonLab/PoonLab#62]
I could not upload the pictures of the screen from my phone to the computer...

**Comment by ArtPoon** [comment]
can you just e-mail them to me?

**Comment by ArtPoon** [comment]
Let's check the backup situation on Shinji and then install the new [Ubuntu 18.04](https://www.ubuntu.com/)

**Comment by jzpero** [comment]
All the home folders are being backed up locally on Shinji to `/data/Shinji-home-backup/[username]`. Just by looking at my personal files, it seems to be a daily backup. I can't find (or don't have the superuser access to read) the crontab job to confirm this.

**Comment by ArtPoon** [comment]
Thanks @jzpero - I'll come by with a USB key to upgrade the OS

**Comment by jzpero** [comment]
Steps:
- [x] create Ubuntu 18.04 LTS bootable USB drive
- [ ] Perform benchmark with BEAST on Shinji
- [ ] figure out how to restore home folders, user accounts/permissions/passwords post-upgrade
- [ ] perform install on SSD
- [ ] restore home folders and user accounts
- [ ] update software and packages

**Comment by jzpero** [comment]
BEAST w/o BEAGLE on Ubuntu 18.04 runs benchmark1.xml within 23.7000 minutes, a 3.1% decrease from 24.469 minutes on Ubuntu 16.04.

Still working on BEAGLE support, having issues with BEAST not being able to find the BEAGLE libraries.

**Comment by ArtPoon** [comment]
See #58

**Comment by ArtPoon** [comment]
everything seems to be hunky dory with Ubuntu 18.04!
thanks @jzpero
